Django-test/website/music/urls.py
from django.conf.urls import url
from django.contrib import admin
from .import views

app_name= 'music'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name="detail")
]

Django-test/website/website/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

Django-test/website/music/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length = 250)
    album_title = models.CharField(max_length = 500)
    genre = models.CharField(max_length = 100)
    album_logo = models.CharField(max_length = 1000)

    def __str__(self):
        return self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    file_type=models.CharField(max_length = 10)
    song_title=models.CharField(max_length = 500)

    def __str__(self):
        return self.song_title

Django-test/website/music/views.py
from django.http import HttpResponse, Http404
from django.template import loader
from .models import Album,Song
from django.shortcuts import render, get_object_or_404

# Create your views here.

def index(request):
    all_album= Album.objects.all()
    #template=loader.get_template('music/index.html')
    context={'all_album': all_album}
    #return HttpResponse(template.render(context, request))
    return render(request, 'music/index.html', context)

def detail(request, album_id):
    '''try:
        album= Album.objects.get(pk=album_id)
        context={'album': album}
    except (Album.DoesNotExist):
        raise Http404("Album Does Not Exist")'''
    album=get_object_or_404(Album, pk=album_id)
    context={
        'album':album
    }
    #return HttpResponse("<h1>Details for album ID: "+ str(album_id) +" </h1>")
    return render(request,'music/detail.html', context)

Django-test/website/music/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
   <img src="{{album.album_logo}}" height="400px" width="200px">
   <h1>Album Title: {{album.album_title}}</h1>
   <h3>Album Artist: {{album.artist}}</h3>

   <ul>
       {% for song in album.song_set.all %}
       <li>Song: {{song.song_title}}</li>
       {% endfor %}
   </ul>
   <!--<h1> Details for Album id: {{album.album_title}}</h1>-->

</body>
</html>

Django-test/website/music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
   {% if all_album %}
   <ul>
       {% for album in all_album%}
       <!--<li><a href="/music/{{album.id}}/">{{album.album_title}}</a></li>-->
       <li><a href="{% url 'music:detail' album.id %}">{{album.album_title}}</a></li>
       {% endfor %}
   </ul>
   {% else %}
      <h2>You have no albums in your databse</h2>
   {% endif %}
</body>
</html>